project:
  type: website

website:
  title: "Tyler Parker"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
  page-footer:
    center: "Â© 2025 Tyler Parker | Built with Quarto"

format:
  html:
    theme: flatly
    toc: true
    toc-location: left
    css: styles.css
